### ISSUE TITLE
Server crashes under load (I think)

### ISSUE THREAD

**Issue by trescube** [whosonfirst/go-whosonfirst-pip#14]
I fired up the server with:

`./bin/wof-pip-server -data ~/git/whosonfirst/whosonfirst-data/data -strict ~/git/whosonfirst/whosonfirst-data/meta/wof-country-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-locality-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-county-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-region-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-neighbourhood-latest.csv ~/git/whosonfirst/whosonfirst-data/meta/wof-localadmin-latest.csv`

After ~100k requests of fairly heavy load, I will sometimes get a server crash with the following stack trace:

```
runtime:objectstart Span weird: p=0xcb42bca9ef k=0x65a15e5 s.start=0xc884b0e000 s.limit=0xcca6f46611 s.state=2
fatal error: objectstart: bad pointer in unexpected span

runtime stack:
runtime.throw(0x4cfac0, 0x2b)
    /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7000004988d8 sp=0x7000004988c0
runtime.heapBitsForObject(0xcb42bca9ef, 0x0, 0x0, 0xc800000000, 0x2d51df8)
    /usr/local/go/src/runtime/mbitmap.go:217 +0x287 fp=0x700000498910 sp=0x7000004988d8
runtime.scanblock(0xc856ce3280, 0x30, 0x4e60bc, 0xc820022720)
    /usr/local/go/src/runtime/mgcmark.go:812 +0xef fp=0x700000498998 sp=0x700000498910
runtime.scanframeworker(0x700000498b50, 0x0, 0xc820022720)
    /usr/local/go/src/runtime/mgcmark.go:486 +0x1b9 fp=0x700000498a30 sp=0x700000498998
runtime.scanstack.func1(0x700000498b50, 0x0, 0x1)
    /usr/local/go/src/runtime/mgcmark.go:384 +0x65 fp=0x700000498a78 sp=0x700000498a30
runtime.gentraceback(0x101990, 0xc856ce3278, 0x0, 0xc83a931e00, 0x0, 0x0, 0x7fffffff, 0x700000498c70, 0x0, 0x0, ...)
    /usr/local/go/src/runtime/traceback.go:338 +0xa69 fp=0x700000498ba8 sp=0x700000498a78
runtime.scanstack(0xc83a931e00)
    /usr/local/go/src/runtime/mgcmark.go:407 +0x38e fp=0x700000498cb0 sp=0x700000498ba8
runtime.scang(0xc83a931e00)
    /usr/local/go/src/runtime/proc1.go:422 +0xf3 fp=0x700000498cd0 sp=0x700000498cb0
runtime.markroot(0xc82001a000, 0x198)
    /usr/local/go/src/runtime/mgcmark.go:133 +0x1ba fp=0x700000498d70 sp=0x700000498cd0
runtime.parfordo(0xc82001a000)
    /usr/local/go/src/runtime/parfor.go:110 +0x1d4 fp=0x700000498df8 sp=0x700000498d70
runtime.gcMark(0x142755221f02c255)
    /usr/local/go/src/runtime/mgc.go:1437 +0x113 fp=0x700000498e60 sp=0x700000498df8
runtime.gc.func3()
    /usr/local/go/src/runtime/mgc.go:1089 +0x23 fp=0x700000498e70 sp=0x700000498e60
runtime.systemstack(0xc820025500)
    /usr/local/go/src/runtime/asm_amd64.s:262 +0x79 fp=0x700000498e78 sp=0x700000498e70
runtime.mstart()
    /usr/local/go/src/runtime/proc1.go:674 fp=0x700000498e80 sp=0x700000498e78

goroutine 10 [garbage collection]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820028498 sp=0xc820028490
runtime.gc(0x0)
    /usr/local/go/src/runtime/mgc.go:1097 +0x3d0 fp=0xc820028790 sp=0xc820028498
runtime.backgroundgc()
    /usr/local/go/src/runtime/mgc.go:897 +0x3d fp=0xc8200287c0 sp=0xc820028790
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200287c8 sp=0xc8200287c0
created by runtime.startGC
    /usr/local/go/src/runtime/mgc.go:870 +0x186

goroutine 1 [IO wait, 5 minutes]:
runtime.gopark(0x504eb0, 0x2bf2150, 0x44f508, 0x7, 0xc88400e01b, 0x5)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc87b6d56a0 sp=0xc87b6d5678
runtime.netpollblock(0x2bf2128, 0x72, 0xc87b6d5718)
    /usr/local/go/src/runtime/netpoll.go:338 +0x15e fp=0xc87b6d56e8 sp=0xc87b6d56a0
net.runtime_pollWait(0x2bf2128, 0x72, 0xc820010190)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60 fp=0xc87b6d5708 sp=0xc87b6d56e8
net.(*pollDesc).Wait(0xc851894f40, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a fp=0xc87b6d5728 sp=0xc87b6d5708
net.(*pollDesc).WaitRead(0xc851894f40, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36 fp=0xc87b6d5750 sp=0xc87b6d5728
net.(*netFD).accept(0xc851894ee0, 0x0, 0x2bf2220, 0xc88400e0c0)
    /usr/local/go/src/net/fd_unix.go:408 +0x27c fp=0xc87b6d5850 sp=0xc87b6d5750
net.(*TCPListener).AcceptTCP(0xc84b0b3d30, 0x53370, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d fp=0xc87b6d58b0 sp=0xc87b6d5850
net/http.tcpKeepAliveListener.Accept(0xc84b0b3d30, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2135 +0x41 fp=0xc87b6d58e8 sp=0xc87b6d58b0
net/http.(*Server).Serve(0xc867c73800, 0x2bf21e8, 0xc84b0b3d30, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0xb3 fp=0xc87b6d59d0 sp=0xc87b6d58e8
net/http.(*Server).ListenAndServe(0xc867c73800, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1877 +0x136 fp=0xc87b6d5a60 sp=0xc87b6d59d0
net/http.ListenAndServe(0xc880a07180, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1967 +0x8f fp=0xc87b6d5a88 sp=0xc87b6d5a60
main.main()
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/cmd/wof-pip-server.go:191 +0x16b4 fp=0xc87b6d5f50 sp=0xc87b6d5a88
runtime.main()
    /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc87b6d5fa0 sp=0xc87b6d5f50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc87b6d5fa8 sp=0xc87b6d5fa0

goroutine 17 [syscall, 17 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820040fb8 sp=0xc820040fb0

goroutine 2 [force gc (idle), 2 minutes]:
runtime.gopark(0x504ef0, 0x659b00, 0x45c990, 0xf, 0x14, 0x1)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002c758 sp=0xc82002c730
runtime.goparkunlock(0x659b00, 0x45c990, 0xf, 0xc820000114, 0x1)
    /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002c790 sp=0xc82002c758
runtime.forcegchelper()
    /usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002c7c0 sp=0xc82002c790
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002c7c8 sp=0xc82002c7c0
created by runtime.init.4
    /usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait, 2 minutes]:
runtime.gopark(0x504ef0, 0x659c80, 0x456bc0, 0xd, 0x52314, 0x1)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002cf48 sp=0xc82002cf20
runtime.goparkunlock(0x659c80, 0x456bc0, 0xd, 0x14, 0x1)
    /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002cf80 sp=0xc82002cf48
runtime.bgsweep(0xc820064000)
    /usr/local/go/src/runtime/mgcsweep.go:67 +0x14d fp=0xc82002cfb8 sp=0xc82002cf80
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002cfc0 sp=0xc82002cfb8
created by runtime.gcenable
    /usr/local/go/src/runtime/mgc.go:206 +0x53

goroutine 4 [finalizer wait, 11 minutes]:
runtime.gopark(0x504ef0, 0x67ef30, 0x45c540, 0xe, 0x14, 0x1)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002d718 sp=0xc82002d6f0
runtime.goparkunlock(0x67ef30, 0x45c540, 0xe, 0x2000000014, 0x1)
    /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002d750 sp=0xc82002d718
runtime.runfinq()
    /usr/local/go/src/runtime/mfinal.go:154 +0xaa fp=0xc82002d7c0 sp=0xc82002d750
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002d7c8 sp=0xc82002d7c0
created by runtime.createfing
    /usr/local/go/src/runtime/mfinal.go:135 +0x60

goroutine 5 [syscall, 2 minutes]:
runtime.notetsleepg(0x659cb8, 0x129bcc789, 0x0)
    /usr/local/go/src/runtime/lock_sema.go:264 +0x86 fp=0xc82002df38 sp=0xc82002def8
runtime.timerproc()
    /usr/local/go/src/runtime/time.go:209 +0xde fp=0xc82002dfc0 sp=0xc82002df38
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002dfc8 sp=0xc82002dfc0
created by runtime.addtimerLocked
    /usr/local/go/src/runtime/time.go:116 +0x11f

goroutine 6 [chan receive, 2 minutes]:
runtime.gopark(0x504ef0, 0xc82001a1d8, 0x45b2f0, 0xc, 0x17, 0x3)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002e670 sp=0xc82002e648
runtime.goparkunlock(0xc82001a1d8, 0x45b2f0, 0xc, 0x2d517, 0x3)
    /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002e6a8 sp=0xc82002e670
runtime.chanrecv(0x3195e0, 0xc82001a180, 0x0, 0x1, 0x0)
    /usr/local/go/src/runtime/chan.go:505 +0x901 fp=0xc82002e768 sp=0xc82002e6a8
runtime.chanrecv1(0x3195e0, 0xc82001a180, 0x0)
    /usr/local/go/src/runtime/chan.go:349 +0x2b fp=0xc82002e798 sp=0xc82002e768
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x659ce0)
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/src/github.com/rcrowley/go-metrics/meter.go:221 +0x4b fp=0xc82002e7b8 sp=0xc82002e798
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c0 sp=0xc82002e7b8
created by github.com/rcrowley/go-metrics.NewMeter
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/src/github.com/rcrowley/go-metrics/meter.go:40 +0x154

goroutine 7 [chan receive, 2 minutes]:
runtime.gopark(0x504ef0, 0xc8200f2058, 0x45b2f0, 0xc, 0x17, 0x3)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002ee38 sp=0xc82002ee10
runtime.goparkunlock(0xc8200f2058, 0x45b2f0, 0xc, 0x504f17, 0x3)
    /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002ee70 sp=0xc82002ee38
runtime.chanrecv(0x3195e0, 0xc8200f2000, 0xc82002ef88, 0x2102aa401, 0x650000)
    /usr/local/go/src/runtime/chan.go:505 +0x901 fp=0xc82002ef30 sp=0xc82002ee70
runtime.chanrecv2(0x3195e0, 0xc8200f2000, 0xc82002ef88, 0x1)
    /usr/local/go/src/runtime/chan.go:354 +0x2b fp=0xc82002ef60 sp=0xc82002ef30
github.com/rcrowley/go-metrics.CaptureRuntimeMemStats(0x77d330, 0xc820011210, 0x2540be400)
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/src/github.com/rcrowley/go-metrics/runtime.go:54 +0x5f fp=0xc82002efa8 sp=0xc82002ef60
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002efb0 sp=0xc82002efa8
created by github.com/whosonfirst/go-whosonfirst-pip.NewPointInPolygonMetrics
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/src/github.com/whosonfirst/go-whosonfirst-pip/pip.go:76 +0xbeb

goroutine 18 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc8204de000, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002ff50 sp=0xc82002ff28
runtime.gcBgMarkWorker(0xc820021500)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc82002ffb8 sp=0xc82002ff50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002ffc0 sp=0xc82002ffb8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 11 [mark worker (idle), 2 minutes]:
runtime.gopark(0x504d88, 0xc8204ba000, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820028f50 sp=0xc820028f28
runtime.gcBgMarkWorker(0xc82001c000)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc820028fb8 sp=0xc820028f50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820028fc0 sp=0xc820028fb8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 12 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc87e0c6000, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820029750 sp=0xc820029728
runtime.gcBgMarkWorker(0xc82001d500)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8200297b8 sp=0xc820029750
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200297c0 sp=0xc8200297b8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 13 [mark worker (idle)]:
runtime.gopark(0x504d88, 0x65ab00, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820029f50 sp=0xc820029f28
runtime.gcBgMarkWorker(0xc82001ea00)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc820029fb8 sp=0xc820029f50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820029fc0 sp=0xc820029fb8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 14 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc8204ba000, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002a750 sp=0xc82002a728
runtime.gcBgMarkWorker(0xc820020000)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc82002a7b8 sp=0xc82002a750
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002a7c0 sp=0xc82002a7b8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 19 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc8204c6000, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc8204b4750 sp=0xc8204b4728
runtime.gcBgMarkWorker(0xc820022a00)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204b47b8 sp=0xc8204b4750
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204b47c0 sp=0xc8204b47b8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 20 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc8204de480, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc8204b4f50 sp=0xc8204b4f28
runtime.gcBgMarkWorker(0xc820024000)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204b4fb8 sp=0xc8204b4f50
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204b4fc0 sp=0xc8204b4fb8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 21 [mark worker (idle)]:
runtime.gopark(0x504d88, 0xc820032900, 0x49c080, 0x12, 0x14, 0x0)
    /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc8204b5750 sp=0xc8204b5728
runtime.gcBgMarkWorker(0xc820025500)
    /usr/local/go/src/runtime/mgc.go:1289 +0xf7 fp=0xc8204b57b8 sp=0xc8204b5750
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204b57c0 sp=0xc8204b57b8
created by runtime.gcBgMarkStartWorkers
    /usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 10300366 [runnable]:
bytes.(*Buffer).WriteString(0xc87f2b0d10, 0xcb42bca9ef, 0x5, 0x0, 0x0, 0x0)
    /usr/local/go/src/bytes/buffer.go:138 fp=0xc856ce3280 sp=0xc856ce3278
encoding/json.(*encodeState).string(0xc87f2b0d10, 0xc85d7c9da8, 0xc85d7c9db0, 0xc85d7c9da8, 0x0, 0x0)
    /usr/local/go/src/encoding/json/encode.go:794 +0x230 fp=0xc856ce32f0 sp=0xc856ce3280
encoding/json.stringEncoder(0xc87f2b0d10, 0x326cc0, 0xc85d7c9da0, 0xd8, 0x0)
    /usr/local/go/src/encoding/json/encode.go:546 +0x2c4 fp=0xc856ce33b8 sp=0xc856ce32f0
encoding/json.(*structEncoder).encode(0xc85871daa0, 0xc87f2b0d10, 0x409e20, 0xc85d7c9d90, 0xd9, 0x0)
    /usr/local/go/src/encoding/json/encode.go:582 +0x2c0 fp=0xc856ce3560 sp=0xc856ce33b8
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc87f2b0d10, 0x409e20, 0xc85d7c9d90, 0xd9, 0xc85d7c9d00)
    /usr/local/go/src/encoding/json/encode.go:596 +0x51 fp=0xc856ce3598 sp=0xc856ce3560
encoding/json.(*ptrEncoder).encode(0xc8461a2310, 0xc87f2b0d10, 0x3b5420, 0xc860abec88, 0xd6, 0x0)
    /usr/local/go/src/encoding/json/encode.go:704 +0xea fp=0xc856ce35e8 sp=0xc856ce3598
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc87f2b0d10, 0x3b5420, 0xc860abec88, 0xd6, 0x3b5400)
    /usr/local/go/src/encoding/json/encode.go:709 +0x51 fp=0xc856ce3620 sp=0xc856ce35e8
encoding/json.(*arrayEncoder).encode(0xc8461a2318, 0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x57, 0xc87f2b0d00)
    /usr/local/go/src/encoding/json/encode.go:685 +0x11b fp=0xc856ce3688 sp=0xc856ce3620
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x57, 0x314600)
    /usr/local/go/src/encoding/json/encode.go:692 +0x51 fp=0xc856ce36c0 sp=0xc856ce3688
encoding/json.(*sliceEncoder).encode(0xc8461a2320, 0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x57, 0x0)
    /usr/local/go/src/encoding/json/encode.go:662 +0xb0 fp=0xc856ce36f8 sp=0xc856ce36c0
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x57, 0xc835ee5e00)
    /usr/local/go/src/encoding/json/encode.go:671 +0x51 fp=0xc856ce3730 sp=0xc856ce36f8
encoding/json.(*encodeState).reflectValue(0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x57)
    /usr/local/go/src/encoding/json/encode.go:297 +0x6b fp=0xc856ce3760 sp=0xc856ce3730
encoding/json.(*encodeState).marshal(0xc87f2b0d10, 0x3146c0, 0xc835ee5e20, 0x0, 0x0)
    /usr/local/go/src/encoding/json/encode.go:270 +0xa9 fp=0xc856ce37a8 sp=0xc856ce3760
encoding/json.Marshal(0x3146c0, 0xc835ee5e20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/encoding/json/encode.go:135 +0x83 fp=0xc856ce37e0 sp=0xc856ce37a8
main.main.func1(0x2bf23c8, 0xc87db7b3f0, 0xc877b97a40)
    /Users/stephenhess/git/whosonfirst/go-whosonfirst-pip/cmd/wof-pip-server.go:169 +0x8d9 fp=0xc856ce3b68 sp=0xc856ce37e0
net/http.HandlerFunc.ServeHTTP(0xc85c6d79c0, 0x2bf23c8, 0xc87db7b3f0, 0xc877b97a40)
    /usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc856ce3b88 sp=0xc856ce3b68
net/http.(*ServeMux).ServeHTTP(0xc820016bd0, 0x2bf23c8, 0xc87db7b3f0, 0xc877b97a40)
    /usr/local/go/src/net/http/server.go:1699 +0x17d fp=0xc856ce3be0 sp=0xc856ce3b88
net/http.serverHandler.ServeHTTP(0xc867c73800, 0x2bf23c8, 0xc87db7b3f0, 0xc877b97a40)
    /usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc856ce3c40 sp=0xc856ce3be0
net/http.(*conn).serve(0xc87db7b340)
    /usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc856ce3f98 sp=0xc856ce3c40
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc856ce3fa0 sp=0xc856ce3f98
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by thisisaaronland** [comment]
Curious if it is related to this:

https://github.com/golang/go/issues/13289#issuecomment-157825358

**Comment by trescube** [comment]
Updated to go 1.5.2 and rebuilt, still crashes

**Comment by zerebubuth** [comment]
Does it give any more useful information if it's compiled using the [race detector `-race`](http://blog.golang.org/race-detector)? I don't have much experience chasing down these sorts of errors in Go, but if this was C++ then I'd strongly suspect a race condition causing heap corruption.

**Comment by trescube** [comment]
I'll give it a try

**Comment by thisisaaronland** [comment]
Also, running it with metrics enabled might yield some useful information or at least more-better hint at the problem:

https://github.com/whosonfirst/go-whosonfirst-pip/#metrics
https://github.com/whosonfirst/go-whosonfirst-pip/#memory-usage

**Comment by thisisaaronland** [comment]
```
Stephen Hess [13:59] 
good news!  ran thru the entire lancaster file twice and no crashes or nulls
​[14:00] 
however, there are still some conflicting responses for identical lat/lon inputs
[14:00] 
15 differences over 212,732 inputs, to be exact
​[14:03] 
scratch that, turns out there are some inputs that return 2 neighborhoods and the order got flipped in my comparisons, so they’re not actually differences
​[14:03] 
so i’d say that all those issues can be closed
```
